// ============================================
// Galderma TrackWise AI Autopilot Demo
// Page: CSV Pack - Computer System Validation
// ============================================

import { useState } from 'react'
import { Shield, FileText, Database, Download, Loader2, CheckCircle2 } from 'lucide-react'
import { cn } from '@/lib/utils'
import { generateCSVPack, type CSVPackResult, type CSVPackArtifact } from '@/api/client'
import { GlassPanel } from '@/components/domain/GlassPanel'
import { EmptyState } from '@/components/domain/EmptyState'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { toast } from 'sonner'

// ============================================
// Helper Functions
// ============================================
function getArtifactIcon(artifactType: string) {
  if (artifactType.toLowerCase().includes('compliance') || artifactType.toLowerCase().includes('validation')) {
    return Shield
  }
  if (artifactType.toLowerCase().includes('data') || artifactType.toLowerCase().includes('ledger')) {
    return Database
  }
  return FileText
}

function formatDate(dateString: string) {
  return new Date(dateString).toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  })
}

function downloadArtifact(artifact: CSVPackArtifact) {
  // Generate mock artifact content based on type
  let content = ''

  if (artifact.artifact_type.includes('Validation')) {
    content = `=== ${artifact.title} ===\n\n${artifact.description}\n\nGenerated: ${new Date().toISOString()}\nArtifact ID: ${artifact.artifact_id}\n\nValidation Status: ${artifact.status}\n\n--- Content ---\nThis is a Computer System Validation (CSV) artifact generated by the TrackWise AI Autopilot system.\n\n21 CFR Part 11 Compliance:\n- Electronic signatures validated\n- Audit trail integrity verified\n- System access controls enforced\n- Data integrity confirmed\n\nAll agent decisions have been recorded in the immutable ledger with cryptographic hash chaining.`
  } else if (artifact.artifact_type.includes('Report')) {
    content = `=== ${artifact.title} ===\n\n${artifact.description}\n\nGenerated: ${new Date().toISOString()}\nArtifact ID: ${artifact.artifact_id}\n\nStatus: ${artifact.status}\n\n--- Summary ---\nThis compliance report documents all AI-driven decisions and human approvals for the analyzed cases.\n\nKey Findings:\n- All critical decisions reviewed by Compliance Guardian (Claude Opus)\n- Human-in-the-loop confirmations recorded\n- Policy violations flagged and resolved\n- Resolution quality meets regulatory standards`
  } else {
    content = `=== ${artifact.title} ===\n\n${artifact.description}\n\nGenerated: ${new Date().toISOString()}\nArtifact ID: ${artifact.artifact_id}\n\nStatus: ${artifact.status}\n\n--- Content ---\nThis artifact is part of the Computer System Validation (CSV) pack for TrackWise AI Autopilot.\n\nCompliance Standard: 21 CFR Part 11\nSystem: TrackWise AI Autopilot Demo\nVersion: 1.0.0\n\nAll data in this artifact has been validated and verified by the compliance pipeline.`
  }

  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${artifact.artifact_id}.txt`
  link.click()
  URL.revokeObjectURL(url)
  toast.success(`Downloaded ${artifact.title}`)
}

// ============================================
// CSV Pack Page Component
// ============================================
export default function CSVPack() {
  const [result, setResult] = useState<CSVPackResult | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)

  const handleGenerate = async () => {
    setIsGenerating(true)
    try {
      const packResult = await generateCSVPack()
      setResult(packResult)
      toast.success('CSV Pack generated successfully')
    } catch (error) {
      console.error('Failed to generate CSV Pack:', error)
      toast.error('Failed to generate CSV Pack')
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="px-8 py-6 border-b border-[var(--glass-border)]">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-[var(--text-primary)]">CSV Pack</h1>
            <p className="text-sm text-[var(--text-secondary)] mt-1">
              Computer System Validation (NOT Comma Separated Values!)
            </p>
          </div>
          <Button
            onClick={handleGenerate}
            disabled={isGenerating}
            size="lg"
            className="gap-2"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Shield className="w-4 h-4" />
                Generate Pack
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 p-8 overflow-auto">
        {!result ? (
          <EmptyState
            icon={Shield}
            title="No CSV Pack generated yet"
            description="Click 'Generate Pack' to create compliance documentation for all processed cases"
            action={
              <Button onClick={handleGenerate} disabled={isGenerating} size="lg" className="gap-2">
                {isGenerating ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Shield className="w-4 h-4" />
                    Generate Pack
                  </>
                )}
              </Button>
            }
          />
        ) : (
          <div className="space-y-6">
            {/* Summary Banner */}
            <GlassPanel className="p-6">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h2 className="text-lg font-semibold text-[var(--text-primary)]">
                    CSV Pack Generated
                  </h2>
                  <p className="text-sm text-[var(--text-secondary)] mt-1">
                    Compliance documentation ready for audit
                  </p>
                </div>
                <Badge
                  variant="outline"
                  className="bg-green-500/10 text-green-400 border-green-500/20"
                >
                  <CheckCircle2 className="w-3 h-3 mr-1" />
                  {result.status}
                </Badge>
              </div>

              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-6">
                <div>
                  <div className="text-xs text-[var(--text-muted)] uppercase tracking-wide">
                    Pack ID
                  </div>
                  <div className="text-sm font-mono text-cyan-400 mt-1">
                    {result.pack_id}
                  </div>
                </div>
                <div>
                  <div className="text-xs text-[var(--text-muted)] uppercase tracking-wide">
                    Generated At
                  </div>
                  <div className="text-sm text-[var(--text-primary)] mt-1">
                    {formatDate(result.generated_at)}
                  </div>
                </div>
                <div>
                  <div className="text-xs text-[var(--text-muted)] uppercase tracking-wide">
                    Cases Analyzed
                  </div>
                  <div className="text-sm font-mono text-[var(--text-primary)] mt-1">
                    {result.total_cases_analyzed}
                  </div>
                </div>
                <div>
                  <div className="text-xs text-[var(--text-muted)] uppercase tracking-wide">
                    Compliance Standard
                  </div>
                  <div className="text-sm font-mono text-[var(--text-primary)] mt-1">
                    {result.compliance_standard}
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4 mt-4">
                <div>
                  <div className="text-xs text-[var(--text-muted)] uppercase tracking-wide">
                    Closed Cases
                  </div>
                  <div className="text-sm font-mono text-green-400 mt-1">
                    {result.closed_cases}
                  </div>
                </div>
                <div>
                  <div className="text-xs text-[var(--text-muted)] uppercase tracking-wide">
                    Total Ledger Entries
                  </div>
                  <div className="text-sm font-mono text-[var(--text-primary)] mt-1">
                    {result.total_ledger_entries}
                  </div>
                </div>
              </div>
            </GlassPanel>

            {/* Artifacts Grid */}
            <div>
              <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-4">
                Compliance Artifacts ({result.artifacts.length})
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {result.artifacts.map((artifact) => {
                  const Icon = getArtifactIcon(artifact.artifact_type)
                  return (
                    <GlassPanel key={artifact.artifact_id} className="p-5 hover:border-[var(--brand-primary)]/30 transition-colors">
                      <div className="flex items-start gap-3">
                        <div className="w-10 h-10 rounded-lg bg-[var(--brand-primary)]/10 flex items-center justify-center shrink-0">
                          <Icon className="w-5 h-5 text-[var(--brand-primary)]" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <h4 className="text-sm font-semibold text-[var(--text-primary)] mb-1">
                            {artifact.title}
                          </h4>
                          <p className="text-xs text-[var(--text-secondary)] mb-3 line-clamp-2">
                            {artifact.description}
                          </p>
                          <div className="flex items-center justify-between">
                            <Badge
                              variant="outline"
                              className={cn(
                                'text-[10px]',
                                artifact.status === 'COMPLETE'
                                  ? 'bg-green-500/10 text-green-400 border-green-500/20'
                                  : 'bg-amber-500/10 text-amber-400 border-amber-500/20'
                              )}
                            >
                              {artifact.status}
                            </Badge>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => downloadArtifact(artifact)}
                              className="gap-1 h-7 px-2 text-xs"
                            >
                              <Download className="w-3 h-3" />
                              Download
                            </Button>
                          </div>
                        </div>
                      </div>
                      <div className="mt-3 pt-3 border-t border-[var(--glass-border)]">
                        <div className="flex items-center justify-between text-xs">
                          <span className="text-[var(--text-muted)]">Artifact ID</span>
                          <span className="font-mono text-cyan-400">{artifact.artifact_id}</span>
                        </div>
                        <div className="flex items-center justify-between text-xs mt-1">
                          <span className="text-[var(--text-muted)]">Type</span>
                          <span className="font-mono text-[var(--text-secondary)]">{artifact.artifact_type}</span>
                        </div>
                      </div>
                    </GlassPanel>
                  )
                })}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
